/* Optional Supabase configuration file
   If this file exists the application will automatically connect.
   Generated by Fintrack settings screen.
*/

window.SUPABASE_CONFIG = {
  url: "https://YOUR_PROJECT.supabase.co",
  anonKey: "YOUR_PUBLIC_ANON_KEY"
};
